### ISSUE TITLE
Ironflow access rights differ?

### ISSUE THREAD

**Issue by liamhuber** [pyiron/ironflow#103]
@jan-janssen @JNmpi, I am no longer allowed to push to the ironflow repo, and unlike the other pyiron repos I don't have access to the "settings" tab here. My guess is that the access rights differ, maybe because of how you spun up the repo originally, Joerg? I think it's only coming up now because I seem to have recently transitioned from "owner" to "member" of the organization overall.

Looking at our other repos, I expect the "pyiron"  team needs to be added under the access settings:

<img width="1141" alt="Screen Shot 2022-11-07 at 10 06 20" src="https://user-images.githubusercontent.com/20283329/200383081-79109b0d-ec86-4fa0-9520-dc5ad056f8d1.png">

**Comment by jan-janssen** [comment]
@liamhuber Can you check if it is fixed now? For some reason both `administration` and `pyiron` had only read access.

**Comment by jan-janssen** [comment]
In terms of the `owner` access - If you want to have owner access I can add you again, I just try to come up with some rules who should be owner and to have the administrative group consistent. Currently, the admin access is restricted to people with a permanent position at MPIE and me until all the rights are configured.
