### ISSUE TITLE
Blockly

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/ironflow#16]
As I am now in the scipy bubble, I just heard about `blockly`: https://developers.google.com/blockly The framework is originally developed by Google and had recently been integrated inside Jupyter lab https://github.com/QuantStack/jupyterlab-blockly . You can find the full article on the Jupyter blog 
https://blog.jupyter.org/visual-programming-in-jupyterlab-with-blockly-7731ec3e113c

**Comment by liamhuber** [comment]
That is very neat! As per our brief discussion after the pyiron meeting this week, I agree with Joerg that writing the (potentially acyclic) graphs for workflows using this tool might not be the best choice, but that for the contents of an individual node Blockly should work very well. With this in mind, I'm not sure whether pyiron-blockly integration belongs best here or in [pyiron_gui](https://github.com/pyiron/pyiron_gui). @niklassiemer, either way I'd like to loop you in on the blockly conversation.
