### ISSUE TITLE
Failures in lates one_mode branch

### ISSUE THREAD

**Issue by JNmpi** [pyiron/ironflow#17]
I really like the new double click feature. It makes the gui much more intuitive. However, I realized two bugs:

- When selecting and deselecting a node I cannot select it again. I first have to select another node. This is rather unintuitiv.

- When selecting the ForEach node and double clicking on the canvas nothing happens. I guess the color definition is missing. At least this is the error I get when I try to load my example workflow.

**Comment by liamhuber** [comment]
> - When selecting and deselecting a node I cannot select it again. I first have to select another node. This is rather unintuitiv.

@JNmpi, unfortunately I can't duplicate this on my machine. I agree the described behaviour is bad, but we might need to look at it next time we're on Zoom together so we can track down where it comes from.

> -When selecting the ForEach node and double clicking on the canvas nothing happens. I guess the color definition is missing. At least this is the error I get when I try to load my example workflow.

Yep, your guess was spot-on. Fixed in #19.

**Comment by liamhuber** [comment]
> - When selecting and deselecting a node I cannot select it again. I first have to select another node. This is rather unintuitiv.

Nevermind, I can get this to happen. It occurs only when clicking on the body of the already selected node. IMO this shouldn't even be deselecting it -- it violates the spec draft in `CanvasObject.__doc__`. Shouldn't be hard to fix.

**Comment by liamhuber** [comment]
> > * When selecting and deselecting a node I cannot select it again. I first have to select another node. This is rather unintuitiv.
> 
> Nevermind, I can get this to happen. It occurs only when clicking on the body of the already selected node. IMO this shouldn't even be deselecting it -- it violates the spec draft in `CanvasObject.__doc__`. Shouldn't be hard to fix.

Fixed in #20 now.
