### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by liamhuber** [pyiron/ironflow#34]
This month I'd like to get the repo set up as a pip package and subsequently available on conda-forge. Before this we should briefly pause to make sure the naming/branding is what we want, as this gets difficult to change downstream. I'm content with `ironflow`, but earlier @jan-janssen had expressed some mild surprise it was not `pyiron_ironflow`. @JNmpi any reconsideration since creating the project?

**Comment by JNmpi** [comment]
I have a slight preference leaving the name as is:
- In contrast to the 'real' pyiron packages this was is not built on top of pyiron but supports pyiron. 
- In the name pyiron_ironflow we would have the name 'iron' twice (which sounds a bit strange)
- The term iron connects in my opinion nicely pyiron and iron flow, showing that they have the same roots
- Having it as subrepository pyiron/ironflow provides the connection

I would therefore like to keep it but I am fully open to alternative arguments.

**Comment by jan-janssen** [comment]
I guess the suggestion I have would be `pyironflow`.

**Comment by liamhuber** [comment]
> I guess the suggestion I have would be `pyironflow`.

I actually like this a lot more as long as pyiron gets pronounced in the canonical "pie-ron" way. Many new users fail to do that, leaving us with "pie-eye-ron-flow", which is gross. At the end of the day I think I'm mildly in favour of this new name though.
