### ISSUE TITLE
Colour-code output by readiness

### ISSUE THREAD

**Issue by liamhuber** [pyiron/ironflow#67]
Many nodes require all their input to be properly set before they produce output; some (e.g. Lammps) actually need to be explicitly `run`. It would be nice if data output ports were colour coded (e.g. red/green) based on whether they held real output or just an un-processed None value.

**Comment by JNmpi** [comment]
I very much like this idea. We may even consider to colorcode input ports that are mandatory but did  not yet got the data. Additionally, the color of the node may change depending whether it has run or not.
