### ISSUE TITLE
ipycanvas 0.13.1 breaks mybinder

### ISSUE THREAD

**Issue by liamhuber** [pyiron/ironflow#74]
If I don't [pin ipycanvas to 0.12.0](https://github.com/pyiron/ironflow/pull/73/commits/b0955135ba2321ddbb7c3bd690bbc762064f7a8f), when I launch on MyBinder I get a javascript error whenever I try to display an `ipycanvas.Canvas` object. Stack trace at the end.

I haven't updated ipycanvas on my local machine yet, so I'll try that first and see if it sheds light. Next a bit more digging. Finally a MWE for the [ipycanvas](https://github.com/martinRenou/ipycanvas)/[mybinder](https://github.com/jupyterhub/binderhub) folks that just makes a canvas and fails.

Error:
```
[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'CanvasModel' from module 'ipycanvas'
@https://hub.gke2.mybinder.org/user/pyiron-ironflow-svzivgxp/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.bcbea9feb6e7c4da7530.js?v=bcbea9feb6e7c4da7530:1:74865
asyncFunctionResume@[native code]
@https://hub.gke2.mybinder.org/user/pyiron-ironflow-svzivgxp/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.3e1e5adfd821b9b96340.js?v=3e1e5adfd821b9b96340:1:10738
asyncFunctionResume@[native code]
@https://hub.gke2.mybinder.org/user/pyiron-ironflow-svzivgxp/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.3e1e5adfd821b9b96340.js?v=3e1e5adfd821b9b96340:1:7531
asyncFunctionResume@[native code]
@https://hub.gke2.mybinder.org/user/pyiron-ironflow-svzivgxp/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.3e1e5adfd821b9b96340.js?v=3e1e5adfd821b9b96340:1:5148
asyncFunctionResume@[native code]
handle_comm_open@https://hub.gke2.mybinder.org/user/pyiron-ironflow-svzivgxp/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.3e1e5adfd821b9b96340.js?v=3e1e5adfd821b9b96340:1:3903
@https://hub.gke2.mybinder.org/user/pyiron-ironflow-svzivgxp/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.bcbea9feb6e7c4da7530.js?v=bcbea9feb6e7c4da7530:1:73409
asyncFunctionResume@[native code]
@https://hub.gke2.mybinder.org/user/pyiron-ironflow-svzivgxp/static/lab/jlab_core.1b1fbf0503029f1fe923.js?v=1b1fbf0503029f1fe923:2:981381
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
```

**Comment by liamhuber** [comment]
@niklassiemer any chance you've run into this?

**Comment by niklassiemer** [comment]
> @niklassiemer any chance you've run into this?

No, not yet. However, I am not progressing on the gui right now...

**Comment by liamhuber** [comment]
> > @niklassiemer any chance you've run into this?
> 
> No, not yet. However, I am not progressing on the gui right now...

No worries. Thanks for the quick reply! 😄

**Comment by liamhuber** [comment]
I updated to 0.13.1 on my local machine and it works totally fine. Problem only occurs when I through mybinder into the mix. Will make a separate MWE repo and pursue it with them. In the meantime we can just leave the requirement pinned at 0.12.0 without any harm.
