### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by JNmpi** [pyiron/ironflow#83]
When playing with the present version (ironflow/blink) I realized a few minor issues:

- linspace: clicking on show does not show the vector
- matplotlib appears to be not working (I connected linspace to matplotlib but was unable to get a plot)
- result node does not show an output (I connected it to linspace but it didn't show the vector)
- clicking on linspace show does not work (should show the vector)

**Comment by liamhuber** [comment]
Thanks @JNmpi! I think I know the source: the linspace node doesn't actually produce/update its output until one of its inputs is changed. I should be able to fix this by updating the `place_event` and will try that out. 

In the meantime, can you try again with updating the linspace input? By doing that the rest works fine for me. If it's still a problem for you, could you post a screenshot and any log messages?

Regarding the `Results` node, indeed, at the moment it doesn't really do anything. I can try to make it print its input into the body of its node widget again. Alternatively, we could just get rid of it; most string data should be available in output representation from all the other nodes, and more complex data won't fit inside the node widget body anyhow.

**Comment by JNmpi** [comment]
Thanks @liamhuber! The new version works well and the linspace etc. show the expected behavior. Having an initial update (place_event) would be very useful and make working with ironflow even more intuitive.

I agree that the results node is no longer needed. The new functionality with the show buttom replaces it fully and is more powerful and intuitive.
